from typing import Protocol

from src.vehicle import VehicleProtocol, VehicleSize


class ParkingSpotProtocol(Protocol):
    def is_available(self) -> bool: ...
    def occupy(self, vehicle: VehicleProtocol) -> None: ...
    def vacate(self) -> None: ...
    def spot_number(self) -> int: ...
    def size(self) -> VehicleSize: ...
